config/routes.rb
Rails.application.routes.draw do

  root 'expedientes#index'

  scope(path_names: { new: 'crear', edit: 'editar' }) do
    resources :expedientes do
      resources :movimientos do
        resources :actividades do
          get 'map', path: 'mapa'
          resources :pagos
        end
        get 'report', path: 'reporte'
        get 'ef_report', path: 'informe'
      end
      resources :anticipos
    end

    resources :plantaciones do
      get 'map', path: 'mapa'
      collection do
        get 'mass_edit', path: 'editar'
        put 'mass_update', path: 'actualizar'
      end
      resources :validaciones
    end

    resources :zonas do
      resources :zona_departamentos
    end

    resources :provincias do
      resources :departamentos
    end

    resources :especies, only: [:index], constraints: { format: 'json' }
    resources :generos do
      resources :especies
    end

    resources :titulares
    resources :tecnicos

    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    post "/adauth" => "sessions#create"
  end
end

app/models/expediente.rb
class Expediente < ActiveRecord::Base
  belongs_to :zona
  belongs_to :zona_departamento
  belongs_to :tecnico
  has_many :movimientos
  has_and_belongs_to_many :titulares
  has_many :anticipos

  validates :numero_interno, :numero_expediente, presence: true, uniqueness: true
  validates :numero_interno, format: { with: /[0-9]{2}-[0-9]{3}-[0-9]{3}\/[0-9]{2}/, message: "el formato debe ser ##-###-###/##" }
  validates :numero_expediente, format: { with: /EXP-S05:[0-9]{7}\/[0-9]{4}/, message: "el formato debe ser EXP-S05:#######/####" }, on: :create

  attr_reader :incompleto, :fecha_entrada_desde, :fecha_entrada_hasta, :fecha_salida_desde, :fecha_salida_hasta, :pendiente,
    :estabilidad_fiscal, :etapa, :responsable_id, :validado, :validador_id

  before_save :set_values

  ##
  # Define los valores de zona, departamento y anio a partir del número interno
  def set_values
    if numero_interno_changed?
      self.zona = Zona.find_by_codigo(numero_interno[0..1])
      self.zona_departamento = zona.zona_departamentos.find_by_codigo(numero_interno[3..5]) if zona
      self.anio = numero_interno[11..12].to_i < 80 ? numero_interno[11..12].to_i + 2000 : numero_interno[11..12].to_i + 1900
    end
  end

  def incompleto=(value)
    if !!value == value
      @incompleto = value
    elsif not value.blank?
      @incompleto = (value == "true")
    end
  end

  def pendiente=(value)
    if !!value == value
      @pendiente = value
    elsif not value.blank?
      @pendiente = (value == "true")
    end
  end

  def estabilidad_fiscal=(value)
    if !!value == value
      @estabilidad_fiscal = value
    elsif not value.blank?
      @estabilidad_fiscal = (value == "true")
    end
  end

  def validado=(value)
    if !!value == value
      @validado = value
    elsif not value.blank?
      @validado = (value == "true")
    end
  end

  def etapa=(value)
    @etapa = value unless value.blank?
  end

  def responsable_id=(value)
    @responsable_id = value unless value.blank?
  end

  def fecha_entrada_desde=(value)
    @fecha_entrada_desde = value unless value.blank?
  end

  def fecha_entrada_hasta=(value)
    @fecha_entrada_hasta = value unless value.blank?
  end

  def fecha_salida_desde=(value)
    @fecha_salida_desde = value unless value.blank?
  end

  def fecha_salida_hasta=(value)
    @fecha_salida_hasta = value unless value.blank?
  end

  def validador_id=(value)
    @validador_id = value unless value.blank?
  end

  ##
  # Devuelve la fecha de entrada del último movimiento del expediente
  def ultima_entrada
    movimientos.order(:fecha_entrada).last.fecha_entrada if movimientos.count > 0
  end

  ##
  # Devuelve la fecha de salida del último movimiento del expediente
  def ultima_salida
    movimientos.order(:fecha_salida).last.fecha_salida if movimientos.count > 0
  end

  ##
  # Devuelve el último movimiento del expediente
  def ultimo_movimiento
    movimientos.order(:fecha_salida).last if movimientos.count > 0
  end

  ##
  # Busca los expedientes que coincidan con los atributos definidos en el objeto Expdiente pasado como parámetro
  def self.search(expediente)
    expedientes = all
    if expediente
      expedientes = expedientes.where("numero_interno ILIKE ?", "%#{expediente.numero_interno}%") unless expediente.numero_interno.blank?
      expedientes = expedientes.where(zona_id: expediente.zona_id) unless expediente.zona_id.nil?
      expedientes = expedientes.where(tecnico_id: expediente.tecnico_id) unless expediente.tecnico_id.nil?
      expedientes = expedientes.where("numero_expediente ILIKE ?", "%#{expediente.numero_expediente}%") unless expediente.numero_expediente.blank?
      expedientes = expedientes.where("numero_expediente IS #{'NOT' unless expediente.incompleto} NULL") unless expediente.incompleto.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.responsable_id = ?", expediente.responsable_id) unless expediente.responsable_id.nil?
      expedientes = expedientes.joins(:movimientos).where("expedientes.anio = ? OR movimientos.etapa = ?", expediente.etapa.to_i, expediente.etapa.to_i) unless expediente.etapa.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.fecha_entrada >= ?", expediente.fecha_entrada_desde) unless expediente.fecha_entrada_desde.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.fecha_entrada <= ?", expediente.fecha_entrada_hasta) unless expediente.fecha_entrada_hasta.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.fecha_salida >= ?", expediente.fecha_salida_desde) unless expediente.fecha_salida_desde.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.fecha_salida <= ?", expediente.fecha_salida_hasta) unless expediente.fecha_salida_hasta.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.estabilidad_fiscal = ?", expediente.estabilidad_fiscal) unless expediente.estabilidad_fiscal.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.validador_id IS #{'NOT' if expediente.validado} NULL") unless expediente.validado.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.validador_id = ?", expediente.validador_id) unless expediente.validador_id.nil?
      expedientes = expedientes.where(plurianual: expediente.plurianual) unless expediente.plurianual.nil?
      expedientes = expedientes.where(agrupado: expediente.agrupado) unless expediente.agrupado.nil?
      expedientes = expedientes.where(activo: expediente.activo) unless expediente.activo.nil?
      expedientes = expedientes.joins(:movimientos).where("movimientos.fecha_salida IS #{'NOT' unless expediente.pendiente} NULL") unless expediente.pendiente.nil?
      expedientes = expedientes.distinct
    end
    expedientes
  end
end

app/controllers/expedientes_controller.rb
class ExpedientesController < ApplicationController
  before_action :set_expediente, only: [:show, :edit, :update, :destroy]

  # GET /expedientes
  # GET /expedientes.json
  # GET /expedientes.csv
  def index
    @expediente_filter = params[:expediente] ? Expediente.new(expediente_params) : Expediente.new({incompleto: false})

    @expedientes = policy_scope(Expediente).search(@expediente_filter)
    @expedientes = @expedientes.order(updated_at: :desc)
    @responsables = Responsable.grouped

    respond_to do |format|
      format.html do
        @count = @expedientes.count
        @expedientes = @expedientes.page params[:page]
        redirect_to @expedientes.first if @expedientes.count == 1
      end
      format.csv do
        @filename = "expedientes.csv"
      end
      format.json
    end
  end

  # GET /expedientes/1
  # GET /expedientes/1.json
  def show
    @movimientos = @expediente.movimientos.order(fecha_entrada: :desc)
  end

  # GET /expedientes/new
  def new
    @expediente = Expediente.new
  end

  # GET /expedientes/1/edit
  def edit
  end

  # POST /expedientes
  # POST /expedientes.json
  def create
    @expediente = Expediente.new(expediente_params)

    respond_to do |format|
      if @expediente.save
        format.html { redirect_to @expediente, notice: 'Expediente creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @expediente }
      else
        format.html { render :new }
        format.json { render json: @expediente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expedientes/1
  # PATCH/PUT /expedientes/1.json
  def update
    respond_to do |format|
      if @expediente.update(expediente_params)
        format.html { redirect_to @expediente, notice: 'Expediente actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @expediente }
      else
        format.html { render :edit }
        format.json { render json: @expediente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expedientes/1
  # DELETE /expedientes/1.json
  def destroy
    @expediente.destroy
    respond_to do |format|
      format.html { redirect_to expedientes_url, notice: 'Expediente eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expediente
      @expediente = Expediente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expediente_params
      params.require(:expediente).permit(:numero_interno, :numero_expediente, :tecnico_id, :zona_id,
        :plurianual, :agrupado, :activo, :incompleto, :fecha_entrada_desde, :fecha_entrada_hasta,
        :fecha_salida_desde, :fecha_salida_hasta, :pendiente, :estabilidad_fiscal,
        :etapa, :responsable_id, :validado, :validador_id, titular_ids: [])
    end
end

app/helpers/expedientes_helper.rb
module ExpedientesHelper
end

app/views/expedientes/_expedientes.html.erb
<table id="expedientes" class="table table-hover table-grid">
  <thead>
    <tr>
      <th>ID</th>
      <th nowrap>Número interno</th>
      <th nowrap>Número expediente</th>
      <th>Titular</th>
      <th>Última Entrada</th>
      <th>Última Salida</th>
      <th>Técnico</th>
      <th class="icon">Activo</th>
    </tr>
  </thead>
  <tbody>
    <% @expedientes.each do |expediente| %>
      <tr data-link="<%= expediente_path(expediente) %>">
        <td><%= expediente.id %></td>
        <td nowrap><%= expediente.numero_interno %></td>
        <td nowrap><%= expediente.numero_expediente %></td>
        <td>
          <abbr title="<%= expediente.titulares.map{ |e| e.nombre }.join(' - ') %>" data-length="20"></abbr>
        </td>
        <td><%= l expediente.ultima_entrada if expediente.ultima_entrada %></td>
        <td><%= l expediente.ultima_salida if expediente.ultima_salida %></td>
        <td>
          <% if expediente.tecnico %>
            <abbr title="<%= expediente.tecnico.nombre %>" data-length="20"></abbr>
          <% end %>
        <td class="icon">
          <%= render partial: 'common/boolean_value', locals: {value: expediente.activo} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @expedientes.num_pages > 1 %>
  <div class="well well-sm clearfix">
    <div class="pagination-info pull-left">
      <%= page_entries_info @expedientes %>
    </div>
    <%= paginate @expedientes %>
  </div>
<% end %>

app/views/expedientes/_form.html.erb
<%= bootstrap_form_for @expediente, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" do |f| %>
  <%= render partial: "common/error_messages", locals: { errors: @expediente.errors } %>
  <%= f.text_field :numero_interno, label: "Número interno" %>
  <%= f.text_field :numero_expediente, label: "Número expediente" %>
  <%= f.collection_select :tecnico_id, Tecnico.all.order(:nombre), :id, :nombre, {label: "Técnico", include_blank: true} %>
  <div class="form-group">
    <div class="col-sm-8 col-sm-offset-4">
      <%= f.check_box :plurianual, label: "", "data-label" => "Plurianual" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-8 col-sm-offset-4">
      <%= f.check_box :agrupado, label: "", "data-label" => "Agrupado" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-8 col-sm-offset-4">
      <%= f.check_box :activo, label: "", "data-label" => "Activo" %>
    </div>
  </div>
  <%= f.collection_select :titular_ids, @expediente.titulares, :id, :nombre, {label: "Titulares Asociados", selected: nil}, {multiple: true, size: 5}%>
  <div class="form-group" style="margin-top: -10px;">
    <div class="col-sm-9 col-sm-offset-3">
      <div class="pull-right">
        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#titulares-modal" id="add-titular">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Asociar
        </button>
        <button type="button" class="btn btn-default btn-xs" id="remove-titular">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Eliminar
        </button>
      </div>
    </div>
  </div>
  <hr/>
  <%= f.submit "Guardar", class: "btn btn-primary pull-right", id: "save-expediente" %>
  <%= link_to "Cancelar", :back, class: "btn btn-default", id: "cancel-expediente" %>
<% end %>

<div class="modal fade" id="titulares-modal" tabindex="-1" role="dialog" aria-labelledby="titulares-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title" id="titulares-modal-label">Asociar Titular a Expediente</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <%= bootstrap_form_tag url: titulares_path + '.json', method: "get", remote: true, layout: :inline do |f| %>
              <%= f.text_field "titular[nombre]", hide_label: true, placeholder: "Nombre" %>
              <%= f.text_field "titular[dni]", hide_label: true, placeholder: "DNI" %>
              <%= f.text_field "titular[cuit]", hide_label: true, placeholder: "CUIT" %>
              <%= f.submit "Buscar", class: "btn btn-default", id: "titulares-modal-search" %>
            <% end %>
          </div>
        </div>
        <hr/>
        <div class="row">
          <div class="col-md-12">
            <table class="table" id="titulares-list">
              <thead>
                <tr>
                  <th></th>
                  <th>Nombre</th>
                  <th>DNI</th>
                  <th>CUIT</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button id="titulares-modal-add" type="button" class="btn btn-primary">Asociar</button>
      </div>
    </div>
  </div>
</div>

app/views/expedientes/_search_form.html.erb
<%= bootstrap_form_for expediente, url: expedientes_path, method: "get", layout: :horizontal, label_col: "col-sm-5", control_col: "col-sm-7" do |f| %>
  <%= f.text_field :numero_interno, label: "Número interno" %>
  <%= f.text_field :numero_expediente, label: "Número expediente" %>
  <%= f.collection_select :zona_id, Zona.all.order(:descripcion), :id, :descripcion, {label: "Zona", include_blank: true} %>
  <%= f.number_field :etapa, label: "Año/Etapa", value: expediente.etapa %>
  <% if current_user.editor? %>
    <%= f.date_field :fecha_entrada_desde, label: "Fecha entrada desde", value: expediente.fecha_entrada_desde %>
    <%= f.date_field :fecha_entrada_hasta, label: "Fecha entrada hasta", value: expediente.fecha_entrada_hasta %>
    <%= f.date_field :fecha_salida_desde, label: "Fecha salida desde", value: expediente.fecha_salida_desde %>
    <%= f.date_field :fecha_salida_hasta, label: "Fecha salida hasta", value: expediente.fecha_salida_hasta %>
    <%= f.select :responsable_id, grouped_options_for_select(@responsables, expediente.responsable_id), {label: "Responsable", include_blank: true} %>
    <%= f.collection_select :tecnico_id, Tecnico.all.order(:nombre), :id, :nombre, {label: "Técnico", include_blank: true} %>
    <%= f.select :validador_id, grouped_options_for_select(@responsables, expediente.validador_id), label: "Validador", include_blank: true %>
    <%= render partial: 'common/boolean_field', locals: {form: f, field: :activo, label: "Activo"} %>
    <%= render partial: 'common/boolean_field', locals: {form: f, field: :plurianual, label: "Plurianual"} %>
  <% end %>
  <%= render partial: 'common/boolean_field', locals: {form: f, field: :agrupado, label: "Agrupado"} %>
  <% if current_user.editor? %>
    <%= render partial: 'common/boolean_field', locals: {form: f, field: :pendiente, label: "Para Analizar"} %>
    <%= render partial: 'common/boolean_field', locals: {form: f, field: :validado, label: "Validado"} %>
  <% end %>
  <%= render partial: 'common/boolean_field', locals: {form: f, field: :estabilidad_fiscal, label: "Estabilidad Fiscal"} %>
  <% if current_user.editor? %>
    <%= render partial: 'common/boolean_field', locals: {form: f, field: :incompleto, label: "Incompleto"} %>
  <% end %>
  <hr/>
  <%= f.submit "Buscar", class: "btn btn-primary pull-right", id: "search", "data-url" => expedientes_path %>
  <% if current_user.editor? %>
    <%= f.submit "Exportar a CSV", class: "btn btn-default #{'disabled' unless params[:expediente]}", id: "exporta",
      "data-url" => expedientes_path(format: 'csv'), "data-count" => @count %>
  <% end %>
<% end %>

app/views/expedientes/edit.html.erb
<div class="row">
  <div class="col-md-5">
    <h2>Editar expediente</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/expedientes/index.html.erb
<% content_for :actions do %>
  <% if current_user.editor? %>
    <li>
      <%= link_to new_expediente_path, id: 'nav-new-expediente' do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo Expediente
      <% end %>
    </li>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-3 hidden-print">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Buscador</h3>
      </div>
      <div class="panel-body">
        <%= render partial: 'search_form', locals: {expediente: @expediente_filter} %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <%= render partial: 'expedientes', locals: {expedientes: @expedientes} %>
  </div>
</div>

app/views/expedientes/new.html.erb
<div class="row">
  <div class="col-md-5">
    <h2>Nuevo Expediente</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/expedientes/show.html.erb
<% content_for :actions do %>
  <% if current_user.editor? %>
    <li>
      <%= link_to edit_expediente_path, id: 'nav-edit-expediente' do %>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Editar Expediente
      <% end %>
    </li>
    <li>
      <%= link_to new_expediente_movimiento_path(@expediente), id: 'nav-new-movimiento' do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo Movimiento
      <% end %>
    </li>
  <% end %>
  <% if current_user.admin? %>
    <li>
      <%= link_to expediente_path, id: 'nav-delete-expediente', method: :delete, data: { confirm: '¿Está seguro que desea elminar el Expediente?' } do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Eliminar Expediente
      <% end %>
    </li>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Expediente</h3>
      </div>
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt>ID expediente:</dt>
          <dd><%= @expediente.id %></dd>
          <dt>Número interno:</dt>
          <dd><%= @expediente.numero_interno %></dd>
          <dt>Número expediente:</dt>
          <dd><%= @expediente.numero_expediente %></dd>
          <dt>Titular/es:</dt>
          <dd>
            <ul class="list-unstyled">
              <% @expediente.titulares.each do |titular| %>
                <li><%= link_to titular.nombre, titular %></li>
              <% end %>
            </ul>
          </dd>
          <dt>Técnico:</dt>
          <dd><%= @expediente.tecnico.nombre if @expediente.tecnico %></dd>
          <dt>Zona:</dt>
          <dd><%= @expediente.zona.descripcion if @expediente.zona %></dd>
          <dt>Departamento:</dt>
          <dd><%= @expediente.zona_departamento.descripcion if @expediente.zona_departamento %></dd>
          <dt>Año:</dt>
          <dd><%= @expediente.anio %></dd>
          <dt>Plurianual:</dt>
          <dd>
            <%= render partial: 'common/boolean_value', locals: {value: @expediente.plurianual} %>
          </dd>
          <dt>Agrupado:</dt>
          <dd>
            <%= render partial: 'common/boolean_value', locals: {value: @expediente.agrupado} %>
          </dd>
          <dt>Última Entrada:</dt>
          <dd><%= l @expediente.ultima_entrada if @expediente.ultima_entrada%></dd>
          <dt>Última Salida:</dt>
          <dd><%= l @expediente.ultima_salida if @expediente.ultima_salida %></dd>
        </dl>
      </div>
      <div class="panel-footer">
        <%= render partial: 'common/boolean_label', locals: {value: @expediente.activo, true_label: "Activo", false_label: "Inactivo"} %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#movimientos-tab" aria-controls="movimientos-tab" role="tab" data-toggle="tab">Movimientos</a>
      </li>
      <% if @expediente.anticipos.count > 0 %>
        <li role="presentation">
          <a href="#anticipos-tab" aria-controls="anticipos-tab" role="tab" data-toggle="tab">Anticipos</a>
        </li>
      <% end %>
    </ul>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="movimientos-tab">
        <%= render partial: 'movimientos/movimientos', locals: {movimientos: @movimientos} %>
      </div>
      <div role="tabpanel" class="tab-pane" id="anticipos-tab">
        <% if @expediente.anticipos.count > 0 %>
          <%= render partial: 'anticipos/anticipos', locals: {anticipos: @expediente.anticipos} %>
        <% end %>
      </div>
    </div>
  </div>
</div>