config/routes.rb
Rails.application.routes.draw do

  root 'expedientes#index'

  scope(path_names: { new: 'crear', edit: 'editar' }) do
    resources :expedientes do
      resources :movimientos do
        resources :actividades do
          get 'map', path: 'mapa'
          resources :pagos
        end
        get 'report', path: 'reporte'
        get 'ef_report', path: 'informe'
      end
      resources :anticipos
    end

    resources :plantaciones do
      get 'map', path: 'mapa'
      collection do
        get 'mass_edit', path: 'editar'
        put 'mass_update', path: 'actualizar'
      end
      resources :validaciones
    end

    resources :zonas do
      resources :zona_departamentos
    end

    resources :provincias do
      resources :departamentos
    end

    resources :especies, only: [:index], constraints: { format: 'json' }
    resources :generos do
      resources :especies
    end

    resources :titulares
    resources :tecnicos

    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    post "/adauth" => "sessions#create"
  end
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  belongs_to :provincia
  has_many :plantaciones
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_provincia
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = @provincia.departamentos.order(:nombre)
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = @provincia.departamentos.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = @provincia.departamentos.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to [@provincia, @departamento], notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: [@provincia, @departamento] }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to [@provincia, @departamento], notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: [@provincia, @departamento] }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to provincia_departamentos_url(@provincia), notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    def set_provincia
      @provincia = Provincia.find(params[:provincia_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:provincia_id, :nombre)
    end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
<% if @departamento.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

    <ul>
    <% @departamento.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :provincia_id %><br>
  <%= f.collection_select :provincia_id, Provincia.all, :id, :nombre %>
</div>

<div class="field">
  <%= f.label :nombre %><br>
  <%= f.text_field :nombre %>
</div>

<div class="field">
  <%= f.label :codigo %><br>
  <%= f.text_field :codigo %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= form_for [@provincia, @departamento], url: provincia_departamento_path(@provincia, @departamento) do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Show', [@provincia, @departamento] %> |
<%= link_to 'Back', provincia_departamentos_path(@provincia) %>

app/views/departamentos/index.html.erb
<h1>Listing departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Provincia</th>
      <th>Nombre</th>
      <th>Código</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.provincia_id %></td>
        <td><%= departamento.nombre %></td>
        <td><%= departamento.codigo %></td>
        <td><%= link_to 'Show', [@provincia, departamento] %></td>
        <td><%= link_to 'Edit', edit_provincia_departamento_path(@provincia, departamento) %></td>
        <td><%= link_to 'Destroy', [@provincia, departamento], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_provincia_departamento_path(@provincia) %>

<br>

<%= link_to 'Provincia', provincia_path(@provincia) %>

app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= form_for [@provincia, @departamento], url: provincia_departamentos_path(@provincia, @departamento) do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Back', provincia_departamentos_path(@provincia) %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zona:</strong>
  <%= @departamento.provincia_id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @departamento.nombre %>
</p>


<p>
  <strong>Código:</strong>
  <%= @departamento.codigo %>
</p>

<%= link_to 'Edit', edit_provincia_departamento_path(@provincia, @departamento) %> |
<%= link_to 'Back', provincia_departamentos_path(@provincia) %>