config/routes.rb
Rails.application.routes.draw do

  root 'expedientes#index'

  scope(path_names: { new: 'crear', edit: 'editar' }) do
    resources :expedientes do
      resources :movimientos do
        resources :actividades do
          get 'map', path: 'mapa'
          resources :pagos
        end
        get 'report', path: 'reporte'
        get 'ef_report', path: 'informe'
      end
      resources :anticipos
    end

    resources :plantaciones do
      get 'map', path: 'mapa'
      collection do
        get 'mass_edit', path: 'editar'
        put 'mass_update', path: 'actualizar'
      end
      resources :validaciones
    end

    resources :zonas do
      resources :zona_departamentos
    end

    resources :provincias do
      resources :departamentos
    end

    resources :especies, only: [:index], constraints: { format: 'json' }
    resources :generos do
      resources :especies
    end

    resources :titulares
    resources :tecnicos

    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    post "/adauth" => "sessions#create"
  end
end

app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
  has_many :expedientes

  validates :nombre, presence: true
  validates :cuit, :dni, uniqueness: true, numericality: { only_integer: true }, allow_blank: true
  validates :cuit, length: { is: 11 }, allow_blank: true
  validates :dni, length: { is: 8 }, allow_blank: true

  ##
  # Busca los técnicos que coincidan con los atributos definidos en el objeto Tecnico pasado como parámetro
  def self.search(tecnico)
    tecnicos = all
    if tecnico
      tecnicos = where("nombre ILIKE ?", "%#{tecnico.nombre}%") unless tecnico.nombre.blank?
      tecnicos = tecnicos.where(activo: tecnico.activo) unless tecnico.activo.nil?
      tecnicos = tecnicos.distinct
    end
    tecnicos.order(:nombre)
  end
end

app/controllers/tecnicos_controller.rb
class TecnicosController < ApplicationController
  before_action :set_tecnico, only: [:show, :edit, :update, :destroy]

  # GET /tecnicos
  # GET /tecnicos.json
  def index
    @tecnico = params[:tecnico] ? Tecnico.new(tecnico_params) : Tecnico.new

    @tecnicos = Tecnico.search(@tecnico)
    @tecnicos = @tecnicos.order(updated_at: :desc)
    @tecnicos = @tecnicos.page(params[:page])

  end

  # GET /tecnicos/1
  # GET /tecnicos/1.json
  def show
    @expedientes = policy_scope(@tecnico.expedientes).distinct.page params[:page]
  end

  # GET /tecnicos/new
  def new
    @tecnico = Tecnico.new
  end

  # GET /tecnicos/1/edit
  def edit
  end

  # POST /tecnicos
  # POST /tecnicos.json
  def create
    @tecnico = Tecnico.new(tecnico_params)

    respond_to do |format|
      if @tecnico.save
        format.html { redirect_to @tecnico, notice: 'Tecnico creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @tecnico }
      else
        format.html { render :new }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tecnicos/1
  # PATCH/PUT /tecnicos/1.json
  def update
    respond_to do |format|
      if @tecnico.update(tecnico_params)
        format.html { redirect_to @tecnico, notice: 'Tecnico actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @tecnico }
      else
        format.html { render :edit }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tecnicos/1
  # DELETE /tecnicos/1.json
  def destroy
    @tecnico.destroy
    respond_to do |format|
      format.html { redirect_to tecnicos_url, notice: 'Tecnico eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tecnico
      @tecnico = Tecnico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tecnico_params
      params.require(:tecnico).permit(:nombre, :dni, :cuit, :activo)
    end
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/tecnicos/_form.html.erb
<%= bootstrap_form_for @tecnico, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9" do |f| %>
  <%= render partial: "common/error_messages", locals: { errors: @tecnico.errors } %>
  <%= f.text_field :nombre, label: "Nombre" %>
  <%= f.text_field :dni, label: "DNI" %>
  <%= f.text_field :cuit, label: "CUIT" %>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <%= f.check_box :activo, label: "", "data-label" => "Activo" %>
    </div>
  </div>
  <hr/>
  <%= link_to "Cancelar", :back, class: "btn btn-default" %>
  <%= f.submit "Guardar", class: "btn btn-primary pull-right", id: "save-tecnico" %>
<% end %>

app/views/tecnicos/_search_form.html.erb
<%= bootstrap_form_for tecnico, url: tecnicos_path, method: "get", layout: :horizontal, label_col: "col-sm-5", control_col: "col-sm-7" do |f| %>
  <%= f.text_field :nombre, label: "Nombre" %>
  <%= f.text_field :dni, label: "DNI" %>
  <%= f.text_field :cuit, label: "CUIT" %>
  <%= render partial: 'common/boolean_field', locals: {form: f, field: :activo, label: "Activo"} %>
  <hr/>
  <%= f.submit "Buscar", class: "btn btn-primary pull-right", id: "search" %>
<% end %>

app/views/tecnicos/_tecnicos.html.erb
<table class="table table-hover table-grid" id="tecnicos">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>DNI</th>
      <th>CUIT</th>
      <th class="icon">Activo</th>
    </tr>
  </thead>
  <tbody>
    <% tecnicos.each do |tecnico| %>
      <tr data-link="<%= tecnico_path(tecnico) %>">
        <td><%= tecnico.id %></td>
        <td><%= tecnico.nombre %></td>
        <td><%= tecnico.dni %></td>
        <td><%= tecnico.cuit %></td>
        <td class="icon">
           <%= render partial: 'common/boolean_value', locals: {value: tecnico.activo} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="well well-sm clearfix">
  <div class="pagination-info pull-left">
    <%= page_entries_info tecnicos %>
  </div>
  <%= paginate tecnicos %>
</div>

app/views/tecnicos/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <h2>Editar Técnico</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/tecnicos/index.html.erb
<% content_for :actions do %>
  <% if current_user.admin? %>
    <li>
      <%= link_to new_tecnico_path, id: "nav-new-tecnico" do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo Técnico
      <% end %>
    </li>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Buscador</h3>
      </div>
      <div class="panel-body">
        <%= render partial: 'search_form', locals: {tecnico: @tecnico} %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <%= render partial: 'tecnicos', locals: {tecnicos: @tecnicos} %>
  </div>
</div>

app/views/tecnicos/new.html.erb
<div class="row">
  <div class="col-md-4">
    <h2>Nuevo Técnico</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/tecnicos/show.html.erb
<% content_for :actions do %>
  <% if current_user.admin? %>
    <li>
      <%= link_to edit_tecnico_path(@tecnico), id: "nav-edit-tecnico" do %>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Editar Técnico
      <% end %>
    </li>
    <li>
      <%= link_to tecnico_path(@tecnico), id: "nav-delete-tecnico", method: :delete,
        data: { confirm: '¿Está seguro que desea eliminar el Técnico?' } do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Eliminar Técnico
      <% end %>
    </li>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Técnico</h3>
      </div>
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt>Nombre:</dt>
          <dd><%= @tecnico.nombre %></dd>
          <dt>DNI:</dt>
          <dd><%= @tecnico.dni %></dd>
          <dt>CUIT:</dt>
          <dd><%= @tecnico.cuit %></dd>
          <dt>Activo:</dt>
          <dd>
            <%= render partial: 'common/boolean_value', locals: {value: @tecnico.activo} %>
          </dd>
        </dl>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <h4>Expedientes</h4>
    <%= render partial: 'expedientes/expedientes', locals: {expedientes: @expedientes} %>
  </div>
</div>