config/routes.rb
Rails.application.routes.draw do

  root 'expedientes#index'

  scope(path_names: { new: 'crear', edit: 'editar' }) do
    resources :expedientes do
      resources :movimientos do
        resources :actividades do
          get 'map', path: 'mapa'
          resources :pagos
        end
        get 'report', path: 'reporte'
        get 'ef_report', path: 'informe'
      end
      resources :anticipos
    end

    resources :plantaciones do
      get 'map', path: 'mapa'
      collection do
        get 'mass_edit', path: 'editar'
        put 'mass_update', path: 'actualizar'
      end
      resources :validaciones
    end

    resources :zonas do
      resources :zona_departamentos
    end

    resources :provincias do
      resources :departamentos
    end

    resources :especies, only: [:index], constraints: { format: 'json' }
    resources :generos do
      resources :especies
    end

    resources :titulares
    resources :tecnicos

    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    post "/adauth" => "sessions#create"
  end
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
  has_many :departamentos
  has_many :plantaciones
end

app/controllers/provincias_controller.rb
class ProvinciasController < ApplicationController
  before_action :set_provincia, only: [:show, :edit, :update, :destroy]

  # GET /provincias
  # GET /provincias.json
  def index
    @provincias = Provincia.all.order(:nombre)
  end

  # GET /provincias/1
  # GET /provincias/1.json
  def show
  end

  # GET /provincias/new
  def new
    @provincia = Provincia.new
  end

  # GET /provincias/1/edit
  def edit
  end

  # POST /provincias
  # POST /provincias.json
  def create
    @provincia = Provincia.new(provincia_params)

    respond_to do |format|
      if @provincia.save
        format.html { redirect_to @provincia, notice: 'Provincia was successfully created.' }
        format.json { render :show, status: :created, location: @provincia }
      else
        format.html { render :new }
        format.json { render json: @provincia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provincias/1
  # PATCH/PUT /provincias/1.json
  def update
    respond_to do |format|
      if @provincia.update(provincia_params)
        format.html { redirect_to @provincia, notice: 'Provincia was successfully updated.' }
        format.json { render :show, status: :ok, location: @provincia }
      else
        format.html { render :edit }
        format.json { render json: @provincia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provincias/1
  # DELETE /provincias/1.json
  def destroy
    @provincia.destroy
    respond_to do |format|
      format.html { redirect_to provincias_url, notice: 'Provincia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provincia
      @provincia = Provincia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provincia_params
      params.require(:provincia).permit(:nombre)
    end
end

app/views/provincias/_form.html.erb
<%= form_for(@provincia) do |f| %>
  <% if @provincia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provincia.errors.count, "error") %> prohibited this provincia from being saved:</h2>

      <ul>
      <% @provincia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provincias/edit.html.erb
<h1>Editing provincia</h1>

<%= render 'form' %>

<%= link_to 'Show', @provincia %> |
<%= link_to 'Back', provincias_path %>

app/views/provincias/index.html.erb
<h1>Listing provincias</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Código</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provincias.each do |provincia| %>
      <tr>
        <td><%= provincia.nombre %></td>
        <td><%= provincia.codigo %></td>
        <td><%= link_to 'Show', provincia %></td>
        <td><%= link_to 'Edit', edit_provincia_path(provincia) %></td>
        <td><%= link_to 'Destroy', provincia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provincia', new_provincia_path %>

app/views/provincias/new.html.erb
<h1>New provincia</h1>

<%= render 'form' %>

<%= link_to 'Back', provincias_path %>

app/views/provincias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @provincia.nombre %>
</p>

<p>
  <strong>Código:</strong>
  <%= @provincia.codigo %>
</p>

<%= link_to 'Edit', edit_provincia_path(@provincia) %> |
<%= link_to 'Back', provincias_path %> |
<%= link_to 'Departamentos', provincia_departamentos_path(@provincia) %>